---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    metadata:
      name: hello
    spec:
      containers:
      - name: hello
        image: registry-docker-registry.knative-build.svc.cluster.local:5000/app-from-source
      restartPolicy: Never